name: cafexpress
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  firebase_auth: ^3.3.5
  google_sign_in: ^5.2.2
  flutter_signin_button: ^2.0.0
  firebase_database: ^9.0.5
  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  device_info_plus: ^3.2.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true